version: '3'

services:
  flask-app:
    image: flask-hello-world
    expose:
      - "5000"
    networks:
      - my-network

  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql-db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    networks:
      - my-network
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - my-network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - /home/apurv/Documents/GY/OSS/lab/docker_codes/dockerAssign3/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app
      - wordpress

networks:
  my-network:
